sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
before_install:
  - sudo apt-get -y install make
script:
  - make .deploy
  - sleep 360 #Sleep so that Windows has time to come up and do installation. AWS recommends 4 mins, but that was too short
  - make .deploy-test
  - make .build
  - make .update
  - make .destroy