sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
# Run builds multi-threaded
env:
  global:
    - MAKEFLAGS="-j 4"
before_install:
  - sudo apt-get -y install make
install:
  - make install-dependencies
script:
  # Since Travis is on AWS, it's public IP isn't the address AWS security groups see. 
  # So we need to drop that restriction for Travis
  - make deploy-ignore-source-ip
after_script:
  - make destroy