sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
before_install:
  - wget -qO- http://checkip.amazonaws.com/
  - wget -qO- http://icanhazip.com/
  - sudo apt-get -y install make
script:
  - make .deploy
after_script:
  - make .destroy