sudo: required
language: minimal
branches:
  only:
    - master
services:
  - docker
env:
  global:
    # Run builds multi-threaded 
    # Since Travis is on AWS, it's public IP isn't the address AWS security groups see. 
    # So we need to drop that restriction for Travis - i.e. allow access from everywhere
    - MAKEFLAGS="-j 4 ACCESS_CIDR=0.0.0.0/0"
before_install:
  - sudo apt-get -y install make
install:
  - make install-dependencies
script:
  - make deploy-ignore-source-ip
after_script:
  - make destroy