version: '3.7'
services:
  gradle:
    image: gradle:${GRADLE_VERSION} # From .env file
    working_dir: /home/gradle/app
    entrypoint: 
      - gradle 
      - --no-daemon
    environment: 
      WINDOWS_TOMCAT_ANSIBLE_DEPLOY_VERSION: ${WINDOWS_TOMCAT_ANSIBLE_DEPLOY_VERSION} # From .env file
    volumes:
    - .:/home/gradle/app
    - gradle:/home/gradle/.gradle
    - gradle-app:/home/gradle/app/.gradle
volumes:
  gradle:
  gradle-app:

    