version: '3.7'
services:
  deploy:
    image: leonyork/ansible:${ANSIBLE_VERSION}
    entrypoint: 'sh -c "$${0} \"$$@\" -i hosts --extra-vars \"ansible_ssh_host=$$HOST ansible_ssh_pass=$$PASSWORD\""'
    working_dir: /app
    volumes:
      - .:/app

    