# Deploys a webapp war to a Tomcat server

- hosts: windows
  tasks:
    - name: Copy the war file {{ web_archive }} as ROOT.war.tmp to {{ tomcat_location }}\webapps
      win_copy:
        src: "{{ web_archive }}"
        dest: "{{ tomcat_location }}\\webapps\\ROOT.war.tmp"
        force: yes

    - name: Remove current war file {{ tomcat_location }}\webapps\ROOT.war
      win_file:
        path: "{{ tomcat_location }}\\webapps\\ROOT.war"
        state: absent

    - name: Wait until the old webapp {{ tomcat_location }}\webapps\ROOT.war is deleted
      win_wait_for:
        path: "{{ tomcat_location }}\\webapps\\ROOT.war"
        state: absent
      register: folder_info

    - name: Rename ROOT.war.tmp to ROOT.war
      win_command: "cmd.exe /c rename {{ tomcat_location }}\\webapps\\ROOT.war.tmp ROOT.war"
      register: cmd_result

    - name: Stop the Tomcat service
      win_command: "cmd.exe /c {{ tomcat_executable }} stop"
      register: cmd_result
      retries: 3
      delay: 10
      until: cmd_result.rc == 0

    - name: Remove current ROOT directory {{ tomcat_location }}\webapps\ROOT
      win_file:
        path: "{{ tomcat_location }}\\webapps\\ROOT"
        state: absent

    - name: Start the Tomcat service
      win_command: "cmd.exe /c {{ tomcat_executable }} start"
      register: cmd_result