version: '3.7'
services:
  deploy:
    image: hashicorp/terraform:${TERRAFORM_VERSION} # From .env file
    entrypoint: 'sh -c ''terraform init -input=false && terraform $${0} "$$@"'''
    command: "apply -input=false -auto-approve"
    working_dir: /app
    environment:
      - AWS_SECRET_KEY_ID=${AWS_SECRET_KEY_ID?You must set the environment variable AWS_SECRET_KEY_ID}
      - AWS_ACCESS_KEY_ID=${AWS_SECRET_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY?You must set the environment variable AWS_SECRET_ACCESS_KEY}
    volumes:
      - .:/app
      - terraform:/app/.terraform
volumes:
  terraform:

    